#!/usr/bin/env sage
"""
Analyze a candidate generated by search_integral.py.

Usage:
    sage sage_analyze.py example_curve.json
    sage sage_analyze.py candidates.json --index 0
"""

import argparse
import json
from sage.all import QQ, RR, EllipticCurve, matrix


def q(s):
    return QQ(s)


def load_candidate(path, index=0):
    with open(path) as f:
        obj = json.load(f)

    if "candidates" in obj:
        return obj["candidates"][index]
    return obj


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json_file")
    ap.add_argument("--index", type=int, default=0)
    args = ap.parse_args()

    c = load_candidate(args.json_file, args.index)
    A = q(c["A"])
    B = q(c["B"])

    # Sage generalized Weierstrass coefficients:
    # y^2 + a1*x*y + a3*y = x^3 + a2*x^2 + a4*x + a6
    E = EllipticCurve(QQ, [1, 0, 0, A, B])

    print("Curve:", E)
    print("a-invariants:", E.a_invariants())
    print("discriminant:", E.discriminant())
    print("j-invariant:", E.j_invariant())

    points = []
    for p in c["points"]:
        P = E(QQ(p["x"]), QQ(p["y"]))
        points.append(P)

    print("Visible points:", len(points))

    # Remove exact duplicate points.
    unique = []
    seen = set()
    for P in points:
        key = tuple(P)
        if key not in seen:
            unique.append(P)
            seen.add(key)

    print("Unique points:", len(unique))

    # Canonical height pairing matrix.
    # A nonsingular pairing matrix proves linear independence over R for the selected
    # non-torsion points, though rigorous certification details depend on the underlying
    # height computations and precision.
    print("Computing canonical height pairing matrix...")
    
    H = E.height_pairing_matrix(unique)
    
    print("Height pairing matrix:")
    print(H)
    
    if H.nrows() > 0:
        print("Height-pairing determinant:", H.det())

    print(
        "NOTE: numerical matrix rank over RR is not used "
        "as a proof of point independence."
    )
    
    if H.nrows() > 0:
        eigs = sorted([abs(x) for x in H.eigenvalues()], reverse=True)

        tol = max(eigs) * 1e-10
        estimated_rank = sum(1 for x in eigs if x > tol)

        print("Height eigenvalues:", eigs)
        print("Estimated numerical span dimension:", estimated_rank)
    
    try:
        print("Regulator of listed points:", E.regulator_of_points(unique))
    except Exception as exc:
        print("regulator_of_points failed:", exc)

    try:
        sat_points, sat_index, sat_regulator = E.saturation(unique)
        print("Saturated basis:")
        for P in sat_points:
            print(P)
        print("Saturation index:", sat_index)
        print("Saturated regulator:", sat_regulator)
    except Exception as exc:
        print("Saturation failed:", exc)
        
    try:
        gens = E.gens(proof=True)
        print("Mordell-Weil generators:")
        for G in gens:
            print(G)
    except Exception as exc:
        print("Generator computation failed:", exc)    

    try:
        print("Relations of visible points to Mordell-Weil generators:")

        search_bound = 6

        for P in unique:
            relation = None

            for a in range(-search_bound, search_bound + 1):
                for b in range(-search_bound, search_bound + 1):
                    for c in range(-search_bound, search_bound + 1):
                        Q = a * gens[0] + b * gens[1] + c * gens[2]

                        if Q == P:
                            relation = (a, b, c)
                            break

                    if relation is not None:
                        break

                if relation is not None:
                    break

            if relation is None:
                print(P, "-> no relation found within bound", search_bound)
            else:
                print(P, "->", relation)

    except Exception as exc:
        print("Relation search failed:", exc)

    print("Torsion subgroup:", E.torsion_subgroup())

    # Useful Sage/eclib hooks; some may be expensive or version-dependent.
    try:
        print("Algebraic rank (PARI 2-descent):", E.rank(algorithm="pari"))
    except Exception as exc:
        print("PARI rank computation unavailable/failed:", exc)

    try:
        print("analytic_rank():", E.analytic_rank())
    except Exception as exc:
        print("analytic_rank unavailable/failed:", exc)


if __name__ == "__main__":
    main()
